### PR TITLE
On Card Pressed Handler

### PR DESCRIPTION
**Pull request by Morji789**
An handler when card pressed, the same as OnButtonPressed

example:

    ScaleformUI.Scaleforms.JobMissionSelector.Cards[1].OnCardPressed = function()
         print("Card Pressed")
    end

### CODE REVIEW

**Comment by manups4e** [comment]
this is awesome! Could you add the C# event too? if not i'll merge and do it myself.. i'd love to have all in 1 commit

**Comment by Morji789** [comment]
I'm not strong at C#, i would rather you doing it

**Comment by manups4e** [comment]
a good opportunity to start learning the language of the Masters u.u anyway don't worry i'll handle it

**Comment by manups4e** [comment]
also.. i just noticed you handled JobSelectionCard.. what about the 3 buttons?

**Comment by Morji789** [comment]
> a good opportunity to start learning the language of the Masters u.u anyway don't worry i'll handle it

I will don't worry

**Comment by manups4e** [comment]
also i would suggest testing your code before doing a pull request.. i didn't have time to check.. and your code resulted in an error...
image
by missing a comma.

**Pull request merged**
