### PR TITLE
C#: Instructional button fixes

### PR DESCRIPTION
**Pull request by QuadrupleTurbo**
• Fixed on screen keyboard instructional button press conflicts.
• Added a force update method to refresh the button text.

### CODE REVIEW

**Comment by manups4e** [comment]
why the force reload is static? Does it have to be?

**Comment by QuadrupleTurbo** [comment]
yes from what I've tested

**Comment by manups4e** [comment]
The object is instanced 🤔 I'll have a look in the afternoon

**Comment by QuadrupleTurbo** [comment]
alrighty 👍🏻

**Comment by Local9** [comment]
Isn't your fault, but `_` on non-private fields.

**Comment by manups4e** [comment]
added manually in https://github.com/manups4e/ScaleformUI/commit/53e730af82cfca8e4fde107a7d67c20b4257176f , you call this by ScaleformUI.ScaleformUI.InstructionalButtons.ForceUpdate()

**Pull request closed without merging**
