### PR TITLE
feat: mono v2 update

### PR DESCRIPTION
**Pull request by Local9**
Missing Alignment, Text, and Rectangle in mono v2 -> https://github.com/thorium-cfx/mono_v2_get_started/issues/16

### CODE REVIEW

**Comment by Local9** [comment]
PR now builds, those elements we should update and just have the `UIResRectangle` and `UIResText` do them instead.

**Comment by manups4e** [comment]
image

when i tried opening the menu

**Comment by manups4e** [comment]
also i get this on resource start

```
[     55781] [FiveM_b2802_GT]             MainThrd/ Failed to instantiate instance of script ScaleformUI.ScaleformUI: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MethodAccessException: Transparent method CitizenFX.Core.EventHandlerSet:op_Addition (CitizenFX.Core.EventHandlerSet,System.Delegate) cannot call Critical method CitizenFX.Core.Func:Create (object,System.Reflection.MethodInfo).
[     55781] [FiveM_b2802_GT]             MainThrd/   at System.Security.SecurityManager.ThrowException (System.Exception ex) [0x00000] in <b575c7ac070e41ffa0751333b6ac9f42>:0 
[     55781] [FiveM_b2802_GT]             MainThrd/   at CitizenFX.Core.EventHandlerSet.op_Addition (CitizenFX.Core.EventHandlerSet entry, System.Delegate deleg) [0x00000] in C:\gl\builds\master\fivem\code\client\clrcore-v2\Interop\EventsManager.cs:184 
[     55781] [FiveM_b2802_GT]             MainThrd/   at ScaleformUI.ScaleformUI..ctor () [0x000b7] in G:\Progetti\source\repos\manups4e\ScaleformUI_V2\ScaleformUI_Csharp\Scaleforms\ScaleformUI\ScaleformUI.cs:43 
[     55781] [FiveM_b2802_GT]             MainThrd/   at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
[     55781] [FiveM_b2802_GT]             MainThrd/   at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in <b575c7ac070e41ffa0751333b6ac9f42>:0 
```

**Comment by Local9** [comment]
Closing this as my forks all fucked up, least we can see the work needed

**Comment by manups4e** [comment]
Yeah we must wait for things to settle in new mono

**Pull request closed without merging**
