### PR TITLE
Add side panels to submenus | Lua

### PR DESCRIPTION
**Pull request by Jordanpkl**
Add side panels to submenus for Lua

### CODE REVIEW

**Comment by manups4e** [comment]
Side panels can be added already to submenus by handling submenu.ParentItem:AddSidePanel

**Comment by manups4e** [comment]
if you think this still could help i'll merge it :) i honestly think you can still do it as the example i showed above.

**Comment by Jordanpkl** [comment]
My bad then, I wasn't able to find if it was possible on the wiki or looking at the examples, and also I didn't know there was a way to get the submenu item so i haven't tried to do it that way 😅

No need to merge this tbh, the example above works great 😄

**Comment by manups4e** [comment]
ahahah ok no problem! Yeah the wiki is a forever work in progress as i'm always fixing, correcting, refactoring, adding and removing so i'm always open to wiki contributions too! 😃 I appreciate the effort to help this resource growing!! Thank you!!

**Comment by manups4e** [comment]
for reference, you can see that whenever a submenu is added
image
it gets a ParentItem and a ParentMenu parameters

**Comment by Jordanpkl** [comment]
I didn't notice that function when I was messing around with it 😅
Thanks for explaining it and for sharing an example on how to do it correctly! 😄

**Comment by manups4e** [comment]
Don't worry! Also if you want to discuss about this you can do it both on the main fivem's discord (would help me growing if more people see my resource being asked) / or you can join my C# dedicated server.. there i discuss of ScaleformUI with everyone interested in it for both lua and c#

**Pull request closed without merging**
