### PR TITLE
Fix UIMenuGridPanel:CirclePosition

### PR DESCRIPTION
**Pull request by matthias-codes**
UIMenuGridPanel would always return the current CirclePosition instead of setting it when a value is parsed, because the Variable Name of the object is the same as the function. (noticed after 4 hours of debugging 🔥)

UIMenuGridPanel:CirclePosition has been changed to UIMenuGridPanel:SetCirclePosition
(would need to be updated in Wiki aswell)

### CODE REVIEW

**Comment by matthias-codes** [comment]
Those 2 commits have been forgotten (forgot to move them other to this "environment"), now they're here, and the panel works flawlessly

https://user-images.githubusercontent.com/92888450/189242319-7d5ad874-76fe-48d2-82cc-d3ce7a6be42d.mp4

**Comment by manups4e** [comment]
I'd prefer to keep the name of the parameter as Circle Position" and not like a setter.. that's because in lua it's both a setter and a getter.. its real name should be SetGetCirclePosition.. lol

**Comment by matthias-codes** [comment]
Should be good now, as you wanted

**Comment by manups4e** [comment]
Awesome thanks!

**Pull request merged**
