### PR TITLE
Add drilling scaleform handler

### PR DESCRIPTION
**Pull request by Mathu-lmn**

### CODE REVIEW

**Comment by Mathu-lmn** [comment]
This PR needs a review, it's working on my end but I'd appreciate some more testing
```lua
local inst = DrillingInstance.New()
inst:Start(function(res)
	print(res)
end)
```
Also needs C# equivalent to be done

**Comment by manups4e** [comment]
What the use of this scaleforn? Can I see a picture?

**Comment by Mathu-lmn** [comment]
https://www.youtube.com/watch?v=Jyia_rFq2do&ab_channel=SMSmith1990
It's the scaleform on the bottom right in this video !

**Comment by dev-drozd** [comment]
> Этот пиар нуждается в сторонке, с моей стороны он работает, но я был бы признателен за дополнительные дополнения.
> 
> ```lua
> local inst = DrillingInstance.New()
> inst:Start(function(res)
> 	print(res)
> end)
> ```
> 
> Также необходимо сделать аналог на C#



> This PR needs a review, it's working on my end but I'd appreciate some more testing
> 
> ```lua
> local inst = DrillingInstance.New()
> inst:Start(function(res)
> 	print(res)
> end)
> ```
> 
> Also needs C# equivalent to be done

Can you provide full documentation on how to use this?

**Comment by Mathu-lmn** [comment]
Hi, the provided script should work as is, everything is handled internally.
Note that this is a draft and not fully implemented for release yet

**Comment by Mathu-lmn** [comment]
Hi, the Lua part works fine for me, feel free to test it and provide feedback. As for the C# part I don't know much about it so I'm just waiting to see if Manu wants it merged in Lua only, or wait for someone to make the C# equivalent !

**Comment by manups4e** [comment]
I didn't merge it because it's a draft..I thought it was on purpose

**Comment by Mathu-lmn** [comment]
Yeah it's a draft because I'm waiting for someone to do the C# equivalent. If it's fine for you to merge this Lua only then I can make it ready for review !

**Pull request merged**
